account/utils: revert username validation
Need to revert this because it introduced a bug:

    ckuehl@death:~$ sudo ~staff/vhost/web.sh
    Traceback (most recent call last):
      File "/opt/share/utils/staff/web/build-vhost-web", line 126, in <module>
        config = "\n\n".join(get_config(domain, conf) for domain, conf in vhosts)
      File "/opt/share/utils/staff/web/build-vhost-web", line 126, in <genexpr>
        config = "\n\n".join(get_config(domain, conf) for domain, conf in vhosts)
      File "/opt/share/utils/staff/web/build-vhost-web", line 65, in get_config
        docroot = os.path.join(utils.web_dir(config['username']), config['docroot'][1:])
      File "/usr/local/lib/python3.2/dist-packages/ocflib/account/utils.py", line 132, in web_dir
        validators.validate_username(user)
      File "/usr/local/lib/python3.2/dist-packages/ocflib/account/validators.py", line 17, in validate_username
        raise ValueError("Username is reserved")
    ValueError: Username is reserved

The tests are going to fail now, so need to find another way to fix
this.